INSERT INTO users (name, surname, birth, email, password, locked, tries) VALUES ('Airouche', 'Meidi', '1988-11-13', 'meidi.airouche@gmail.com', 'vjZn7mxIbux578oxUfoU1A==', false, 0);
INSERT INTO users (name, surname, birth, email, password, locked, tries) VALUES ('User', 'Test', '1989-11-10', 'test@gmail.com', 'vjZn7mxIbux578oxUfoU1A==', true, 3);
INSERT INTO users (name, surname, birth, email, password, locked, tries) VALUES ('UserToLock', 'WillBeLocked', '1989-11-11', 'willbelocked@gmail.com', 'vjZn7mxIbux578oxUfoU1A==', false, 0);
INSERT INTO users (name, surname, birth, email, password, locked, tries) VALUES ('UserUnauthorized', 'UserUnauthorized', '1989-11-12', 'userunauthorized@gmail.com', 'vjZn7mxIbux578oxUfoU1A==', false, 0);
INSERT INTO applications(AUID, name) VALUES('TKP', 'Trello KPI');
INSERT INTO applications(AUID, name) VALUES('FRG', 'Forge Argonot');
INSERT INTO roles(RUID, name) VALUES ('ADM', 'ADMIN');
INSERT INTO roles(RUID, name) VALUES ('USR', 'USER');
INSERT INTO authorizations(id_user, AUID, RUID) VALUES(1, 'FRG', 'ADM');
INSERT INTO authorizations(id_user, AUID, RUID) VALUES(2, 'FRG', 'USR');
INSERT INTO authorizations(id_user, AUID, RUID) VALUES(2, 'TKP', 'USR');
INSERT INTO authorizations(id_user, AUID, RUID) VALUES(3, 'FRG', 'USR');